<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>body_Dashboard Working Capital ReceivablesP_1b8e67</name>
   <tag></tag>
   <elementGuidId>4f3b0e34-87d2-4d78-b3b8-0e4f0a7222b4</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>body</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//body</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>body</value>
      <webElementGuid>363f1916-3f0f-42ce-bdd0-c40328efdca8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch</value>
      <webElementGuid>0fe156fc-d364-42ef-9ee6-99af296b1df8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[1]</value>
      <webElementGuid>f10c0a89-054d-4888-ac66-61dae70986e3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body</value>
      <webElementGuid>e6ad1318-bbf6-4b36-b796-8e24e79b3896</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//body[(text() = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch' or . = 'Dashboard Working Capital ReceivablesPayablesSettlementsReportsInsuranceTredsBeta Version 1.0​UTH Invite17 ›Bank Profile Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameThaigudda  Account Number28451234 Branch IFSCYESB0000653Account TypeCA  MICR560532002 Account Holder NamePTHMandates Create E-Mandate  Create Physical-Mandate Company BranchMain Branch Add as Beneficiary Bank NameYES BANK  Branch NameChaigudda  Account Number28451236 Branch IFSCYESB0000653Account TypeSB  MICR560532002 Account Holder NameDTHMandates Create E-Mandate  Create Physical-Mandate Company Branch​​Add as BeneficiaryBank Name​  Branch Name​  Account Number​ Branch IFSC​Account Type​  MICR​ Account Holder Name​Mandates Create E-Mandate  Create Physical-Mandate SubmitAdd Bankid(&quot;menu-&quot;)/div[@class=&quot;MuiBackdrop-root MuiBackdrop-invisible css-g3hgs1-MuiBackdrop-root-MuiModal-backdrop&quot;]UTH PTuthukpnt@gmail.com+918553619133User ManagementSign Out  UTHBank ProfileManage SubscriptionsConfirm To End Your Session? YesMain Branch')]</value>
      <webElementGuid>8555b773-c52b-4d67-8e4c-40dd260392a1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
